export const SwaggerSummary = {
  AuthRequestChallenge: 'Request a login challenge',
  AuthVerifySignature: 'Verify a wallet signature and issue access token',
  AuthGetProfile: 'Get the authenticated user profile from token',
  ProfileGet: 'Retrieve the authenticated user profile',
  ProfileUpdate: 'Update the authenticated user profile',
} as const;

export const SwaggerTags = {
  Auth: 'Auth',
  Profile: 'Profile',
} as const;

export const SwaggerDescriptions = {
  ProfileGetSuccess: 'User profile retrieved successfully',
  ProfileUpdateSuccess: 'User profile updated successfully',
  BearerAuthDescription: 'Provide the JWT returned by /auth/verify.',
} as const;

export const SwaggerFieldDescriptions = {
  AuthWalletAddress:
    'Ethereum wallet address requesting the authentication challenge',
  WalletAddress: 'Ethereum wallet address associated with the user',
  WalletSignature: 'Hex-encoded signature generated by the wallet',
  LoginMessage: 'Original message presented to the user for signing',
  FullName: 'Full name of the user',
  Username:
    'Unique username identifier composed of letters, numbers, dots, underscores, or hyphens',
  Email: 'Email address for user notifications and communication',
} as const;

export const SwaggerExamples = {
  WalletAddress: '0x1234567890abcdef1234567890abcdef12345678',
  Signature:
    '0x72f1f65c98d8887c7d8d872f98f2238959e569f4b525f1b190913da4f538d3b56c81cb2da001cd20811ac36db4fa20c739ebb1e7a0e88c8d0d203a7955c2d56f1c',
  LoginMessage:
    'Sign in to Wallet\nURI: http://localhost:3000\nWallet: 0x123...\nChain ID: 1\nNonce: 0123456789abcdef',
  FullName: 'Satoshi Nakamoto',
  Username: 'satoshi.n',
  Email: 'satoshi@example.com',
} as const;

export const SwaggerDoc = {
  Title: 'Blockchain API',
  Description: 'API documentation for the blockchain backend services.',
  Version: '1.0.0',
  DocsPath: 'api/docs',
  Bearer: {
    type: 'http',
    scheme: 'bearer',
    bearerFormat: 'JWT',
    description: SwaggerDescriptions.BearerAuthDescription,
  },
} as const;
